chore: tweaks to release.yml ~ 1 file 58+ 26-
.github/workflows/release.yml

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -1,53 +1,85 @@
-name: Release
+name: Release Package
 
 on:
   push:
     branches:
-      - main
+      - "**"
+  issue_comment:
+    types: [created]
 
 concurrency: ${{ github.workflow }}-${{ github.ref }}
 
+permissions:
+  id-token: write
+  contents: write
+  statuses: write
+  pull-requests: write
+
 jobs:
   release:
-    name: Release
+    if: |
+      github.event_name == 'push' || 
+      github.event_name == 'issue_comment' && contains(github.event.comment.body, 'release') && github.event.comment.user.login == github.repository_owner
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout Repo
+      - name: Checkout Repository
         uses: actions/checkout@v4
         with:
           fetch-depth: 0
 
-      - name: Setup Bun
-        uses: oven-sh/setup-bun@v2
-
       - name: Setup Node
         uses: actions/setup-node@v4
         with:
-          node-version: 22
+          node-version: lts/*
+          registry-url: https://registry.npmjs.org
+
+      - name: Setup Bun
+        uses: oven-sh/setup-bun@v2
+        with:
+          bun-version: latest
 
       - name: Install Dependencies
-        run: bun install --no-save
+        run: bun install --frozen-lockfile
 
-      - name: Build
+      - name: Build Package
         run: bun run build
 
-      - id: CHECK_TOKENS
-        name: Check if TOKENS are configured
+      - name: Release Package
         run: |
-          if [ -z "${{ secrets.GITHUB_TOKEN }}" ] || [ -z "${{ secrets.NPM_TOKEN }}" ]; then
-            echo "TOKENS are not configured. Skipping changeset actions."
-            echo "NOT_FOUND=true" >> $GITHUB_OUTPUT
+          PACKAGE_NAME=$(bunx json -f package.json -a name)
+          npm view "$PACKAGE_NAME" 2>/dev/null || { echo "$PACKAGE_NAME does not exist in the npm registry. Skipping publish."; exit 0; }
+          PACKAGE_VERSION=$(bunx json -f package.json -a version)
+          VERSIONS=$(npm view $PACKAGE_NAME dist-tags --json)
+          LATEST_VERSION=$(echo $VERSIONS | bunx json latest)
+          if [[ $GITHUB_EVENT_NAME == 'issue_comment' ]]; then
+            TAG="test"
+            RELEASE_VERSION="0.0.0-$(openssl rand -hex 7)"
+          elif [[ $PACKAGE_VERSION != $LATEST_VERSION ]]; then
+            RELEASE_VERSION=$PACKAGE_VERSION
+            HAS_TAG=$(echo $PACKAGE_VERSION | grep -o '[a-zA-Z]*' | head -n 1)
+            TAG=$([[ -n "$HAS_TAG" ]] && echo $HAS_TAG || echo "latest")
+          else
+            TAG="canary"
+            RELEASE_VERSION=$(bunx semver $LATEST_VERSION -i minor)
+            TAGGED_VERSION=$(echo $VERSIONS | bunx json $TAG)
+            RELEASE_VERSION=$([[ $TAGGED_VERSION == $RELEASE_VERSION* ]] && bunx semver $TAGGED_VERSION -i prerelease || echo $RELEASE_VERSION-$TAG.0)
           fi
+          bunx json -I -f package.json -e "this.version=\"$RELEASE_VERSION\""
+          npm publish --provenance --access public --no-git-checks --tag $TAG
 
-      - id: changesets
-        name: Create a release pull request or publish to npm
-        if: steps.CHECK_TOKENS.outputs.NOT_FOUND != 'true'
-        uses: changesets/action@v1
-        with:
-          title: "chore(release): version packages"
-          commit: "chore(release): version packages"
-          version: node .github/changeset-version.js
-          publish: bun run publish:latest
+          PACKAGE_URL="https://www.npmjs.com/package/$PACKAGE_NAME/v/$RELEASE_VERSION"
+          if [[ $GITHUB_EVENT_NAME == 'issue_comment' ]]; then
+            PR_NUMBER=$(echo "${{ github.event.issue.pull_request.url }}" | grep -o '[0-9]*$')
+            curl -fsSL -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/$GITHUB_REPOSITORY/issues/$PR_NUMBER/comments" \
+              -d "{\"body\": \"Test package released - [\`$PACKAGE_NAME@$RELEASE_VERSION\`]($PACKAGE_URL)\"}" >/dev/null \
+              && echo "🟢 Release comment to PR added!" || echo "🔴 Failed to add release comment to PR."
+          elif [[ $GITHUB_EVENT_NAME == 'push' ]]; then
+            curl -fsSL -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/$GITHUB_REPOSITORY/commits/$GITHUB_SHA/comments" \
+              -d "{\"body\": \"Package released - [\`$PACKAGE_NAME@$RELEASE_VERSION\`]($PACKAGE_URL)\"}" >/dev/null \
+              && echo "🟢 Release comment added!" || echo "🔴 Failed to add release comment."
+            curl -fsSL -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/$GITHUB_REPOSITORY/statuses/$GITHUB_SHA" \
+              -d "{\"state\": \"success\", \"context\": \"Package released\", \"description\": \"$PACKAGE_NAME@$RELEASE_VERSION\", \"target_url\": \"$PACKAGE_URL\"}" >/dev/null \
+              && echo "🟢 Release status updated!" || echo "🔴 Failed to update release status."
+          fi
         env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
+          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
